name: Build FFXIV Zoom Hack

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17,18)'
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore .\FFXIVZoomHack.sln

      - name: Build release application
        run: msbuild /t:rebuild /p:Configuration=Release .\FFXIVZoomHack.sln

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "FFXIVZoomHack.exe"
          path: "FFXIVZoomHack\\bin\\Release\\FFXIVZoomHack.exe"
          if-no-files-found: 'error'
